Jakarta Support
cloudfoundry/java-buildpack-client-certificate-mapper pull request #9
Opened 2023-11-13 22:36 UTC by nebhale

This change updates the project to support both the javax and jakarta namespaces for JEE projects.  It does this by creating two separate Maven projects, one for each, which are then shaded into a single JAR used by everyone.  The contents of `META-INF/services` and `META-INF/spring.factories` route to the correct implementation preventing class loading problems.

2023-11-14 04:01 UTC, anthonydahanne requested changes
Thanks so much @nebhale for simplifying everything about Jakarta support!

Since we now deploy to Maven Central, we'll need a bit more XML to add developers, javadoc, licence, url and scm (like I did in the other [PR](https://github.com/cloudfoundry/java-buildpack-client-certificate-mapper/pull/8/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R38))
But we'll add that with David when we test.

Please let me know about the PR comments I left! I'm curious to know your take on those.
Thanks again!

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper-jakarta/pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
why keeping this naming `x.y.z.BUILD-SNAPSHOT` ?
Aren't most up to date spring projects using `x.y.z-SNAPSHOT` ?

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper-jakarta/src/main/java/org/cloudfoundry/router/jakarta/ClientCertificateMapper.java
> +    static final String ATTRIBUTE = "javax.servlet.request.X509Certificate";
```suggestion
    static final String ATTRIBUTE = "jakarta.servlet.request.X509Certificate";
```

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper-jakarta/src/main/java/org/cloudfoundry/router/jakarta/ClientCertificateMapper.java
> + * A Servlet {@link Filter} that translates the {@code X-Forwarded-Client} HTTP header to the {@code javax.servlet.request.X509Certificate} Servlet attribute.  This implementation handles both
```suggestion
 * A Servlet {@link Filter} that translates the {@code X-Forwarded-Client} HTTP header to the {@code jakarta.servlet.request.X509Certificate} Servlet attribute.  This implementation handles both
```

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper-jakarta/pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
```suggestion
        <version>2.0.0-SNAPSHOT</version>
```

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper-javax/pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
```suggestion
        <version>2.0.0-SNAPSHOT</version>
```

2023-11-14 04:01 UTC, anthonydahanne commented on java-buildpack-client-certificate-mapper/pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
```suggestion
        <version>2.0.0-SNAPSHOT</version>
```

2023-11-14 04:01 UTC, anthonydahanne commented on pom.xml
> +    <version>2.0.0.BUILD-SNAPSHOT</version>
```suggestion
    <version>2.0.0-SNAPSHOT</version>
```

2023-11-14 04:01 UTC, anthonydahanne commented on pom.xml
> +                    <artifactId>artifactory-maven-plugin</artifactId>
I don't think this plugin utilization is relevant / needed anymore.
With a slight change to [deploy.sh](https://github.com/cloudfoundry/java-buildpack-client-certificate-mapper/pull/8/files#diff-d498a12aa774941c9553350f6bc684a7bb2a70d6b6a2c1fb0619dd90907e8d4dR10) and the [concourse pipeline](https://github.com/pivotal-cf/java-experience-concourse/pull/23/files#diff-d7c0f3daa68586740aac7dfbb56cb7d1fb0979b644700ea0aeaf260e84dd4ea1R31) , we conform to other Java experience projects and don't rely on plugins not coming from central.

2023-11-16 15:39 UTC, nebhale commented on java-buildpack-client-certificate-mapper-jakarta/pom.xml
> +        <version>2.0.0.BUILD-SNAPSHOT</version>
Feel free to change this as you choose.  I did the minimum change necessary to get this PR into place.

2023-11-16 15:57 UTC, nebhale commented on pom.xml
> +                    <artifactId>artifactory-maven-plugin</artifactId>
Feel free to remove as you desire.

2023-11-22 15:49 UTC, nebhale commented
Nudge @anthonydahanne.

2023-12-01 15:05 UTC, pivotal-david-osullivan approved these changes

2023-12-01 15:05 UTC, merged